version: '3.8'

services:
  postgres:
    container_name: hexagonal-postgres
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_hexagonal
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped